snooze-till-graph-age-minutes: 100000
prefix:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  dcat: http://www.w3.org/ns/dcat#
  schema: https://schema.org/
  org: http://www.w3.org/ns/org#
  dct: http://purl.org/dc/terms/
  mi: http://www.marineinfo.org/ns/ontology#
assert:
  - subjects:
      literal:
        - https://data.emobon.embrc.eu
    paths:
      - "*"
  - subjects: # get the data from all Catalogs , first the catalogs since they can contain more datasets
      SPARQL: >
        SELECT DISTINCT ?o
        WHERE { 
          {?s dcat:catalog ?o . }
          UNION
          {?s a dcat:Catalog . }
        }
    paths:
      - "*"
  - subjects: # get the data from all Datasets
      SPARQL: >
        SELECT DISTINCT ?o
        WHERE { 
          {?s dcat:dataset ?o . }
          UNION
          {?s a dcat:Dataset . }
        }
    paths:
      - "*"