name: Docker Images Build & Push to ghrc.io

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3

      - name: Test the python execution for consistency prior to docker build
        run: |
          echo "Setting up Python env and running tests."
          echo "py=$(which python) pip=$(which pip) flake8=$(which flake8) pytest=$(which pytest)"
          make init 
          . .venv/bin/activate 
          echo "py=$(which python) pip=$(which pip) flake8=$(which flake8) pytest=$(which pytest)"
          make check test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: get_tag
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

      - name: Use tag name
        run: echo ${{ steps.get_tag.outputs.TAG_NAME }}

      - name: Disclose the event_name
        run: echo ${{ github.event_name }}

      - name: Build the Docker image and Push it to the registry-namespace indicated in REG_NS
        run: |
          touch .env                                 # make sure we have one to satisfy the build
          export REG_NS="ghcr.io/emo-bon/emobon"     # sets the public scope for these
          TAG_NAME=${GITHUB_REF#refs/tags/}          # this is the tag name of the release
          echo $TAG_NAME                             # this is the tag name of the release
          # build tag is the same as tag name for releases if this matches the semver format else it is latest

          # The string you want to check

          # The regular expression
          regex="^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\\+([0-9a-zA-Z-]+(\\.[0-9a-zA-Z-]+)*))?$"

          if [[ $TAG_NAME =~ $regex ]]; then
            export BUILD_TAG=$TAG_NAME
          else
            export BUILD_TAG="latest"
          fi
          echo $BUILD_TAG

          if [[ ${{ github.event_name }} == pull_request ]]; then
              echo "for pull requests we only build and test"
              make docker-build docker-test
          else
              echo "for main commits we build, test and push"
              make docker-push
          fi